// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_login.proto

package com.server.msg.protocol;

public final class MsgLogin {
  private MsgLogin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.server.msg.protocol.MsgLogin.login);
  }
  public interface LoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
     */
    boolean hasLoginRequest();
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
     */
    com.server.msg.protocol.MsgLogin.Login.LoginRequest getLoginRequest();
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
     */
    com.server.msg.protocol.MsgLogin.Login.LoginRequestOrBuilder getLoginRequestOrBuilder();

    // optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
     */
    boolean hasLoginResponse();
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
     */
    com.server.msg.protocol.MsgLogin.Login.LoginResponse getLoginResponse();
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
     */
    com.server.msg.protocol.MsgLogin.Login.LoginResponseOrBuilder getLoginResponseOrBuilder();
  }
  /**
   * Protobuf type {@code com.server.msg.protocol.Login}
   *
   * <pre>
   *登录模块
   * </pre>
   */
  public static final class Login extends
      com.google.protobuf.GeneratedMessage
      implements LoginOrBuilder {
    // Use Login.newBuilder() to construct.
    private Login(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Login(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Login defaultInstance;
    public static Login getDefaultInstance() {
      return defaultInstance;
    }

    public Login getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Login(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.server.msg.protocol.MsgLogin.Login.LoginRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = loginRequest_.toBuilder();
              }
              loginRequest_ = input.readMessage(com.server.msg.protocol.MsgLogin.Login.LoginRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loginRequest_);
                loginRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.server.msg.protocol.MsgLogin.Login.LoginResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = loginResponse_.toBuilder();
              }
              loginResponse_ = input.readMessage(com.server.msg.protocol.MsgLogin.Login.LoginResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loginResponse_);
                loginResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.msg.protocol.MsgLogin.Login.class, com.server.msg.protocol.MsgLogin.Login.Builder.class);
    }

    public static com.google.protobuf.Parser<Login> PARSER =
        new com.google.protobuf.AbstractParser<Login>() {
      public Login parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Login(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Login> getParserForType() {
      return PARSER;
    }

    public interface LoginRequestOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string userId = 2;
      /**
       * <code>optional string userId = 2;</code>
       */
      boolean hasUserId();
      /**
       * <code>optional string userId = 2;</code>
       */
      java.lang.String getUserId();
      /**
       * <code>optional string userId = 2;</code>
       */
      com.google.protobuf.ByteString
          getUserIdBytes();
    }
    /**
     * Protobuf type {@code com.server.msg.protocol.Login.LoginRequest}
     */
    public static final class LoginRequest extends
        com.google.protobuf.GeneratedMessage
        implements LoginRequestOrBuilder {
      // Use LoginRequest.newBuilder() to construct.
      private LoginRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private LoginRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final LoginRequest defaultInstance;
      public static LoginRequest getDefaultInstance() {
        return defaultInstance;
      }

      public LoginRequest getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private LoginRequest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 18: {
                bitField0_ |= 0x00000001;
                userId_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_LoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.msg.protocol.MsgLogin.Login.LoginRequest.class, com.server.msg.protocol.MsgLogin.Login.LoginRequest.Builder.class);
      }

      public static com.google.protobuf.Parser<LoginRequest> PARSER =
          new com.google.protobuf.AbstractParser<LoginRequest>() {
        public LoginRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginRequest(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<LoginRequest> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string userId = 2;
      public static final int USERID_FIELD_NUMBER = 2;
      private java.lang.Object userId_;
      /**
       * <code>optional string userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        userId_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(2, getUserIdBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getUserIdBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.server.msg.protocol.MsgLogin.Login.LoginRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.server.msg.protocol.MsgLogin.Login.LoginRequest prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.server.msg.protocol.Login.LoginRequest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.server.msg.protocol.MsgLogin.Login.LoginRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_LoginRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_LoginRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.server.msg.protocol.MsgLogin.Login.LoginRequest.class, com.server.msg.protocol.MsgLogin.Login.LoginRequest.Builder.class);
        }

        // Construct using com.server.msg.protocol.MsgLogin.Login.LoginRequest.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          userId_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_LoginRequest_descriptor;
        }

        public com.server.msg.protocol.MsgLogin.Login.LoginRequest getDefaultInstanceForType() {
          return com.server.msg.protocol.MsgLogin.Login.LoginRequest.getDefaultInstance();
        }

        public com.server.msg.protocol.MsgLogin.Login.LoginRequest build() {
          com.server.msg.protocol.MsgLogin.Login.LoginRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.server.msg.protocol.MsgLogin.Login.LoginRequest buildPartial() {
          com.server.msg.protocol.MsgLogin.Login.LoginRequest result = new com.server.msg.protocol.MsgLogin.Login.LoginRequest(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.userId_ = userId_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.server.msg.protocol.MsgLogin.Login.LoginRequest) {
            return mergeFrom((com.server.msg.protocol.MsgLogin.Login.LoginRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.server.msg.protocol.MsgLogin.Login.LoginRequest other) {
          if (other == com.server.msg.protocol.MsgLogin.Login.LoginRequest.getDefaultInstance()) return this;
          if (other.hasUserId()) {
            bitField0_ |= 0x00000001;
            userId_ = other.userId_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.server.msg.protocol.MsgLogin.Login.LoginRequest parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.server.msg.protocol.MsgLogin.Login.LoginRequest) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string userId = 2;
        private java.lang.Object userId_ = "";
        /**
         * <code>optional string userId = 2;</code>
         */
        public boolean hasUserId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string userId = 2;</code>
         */
        public java.lang.String getUserId() {
          java.lang.Object ref = userId_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            userId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string userId = 2;</code>
         */
        public com.google.protobuf.ByteString
            getUserIdBytes() {
          java.lang.Object ref = userId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            userId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string userId = 2;</code>
         */
        public Builder setUserId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          userId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string userId = 2;</code>
         */
        public Builder clearUserId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          userId_ = getDefaultInstance().getUserId();
          onChanged();
          return this;
        }
        /**
         * <code>optional string userId = 2;</code>
         */
        public Builder setUserIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          userId_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.server.msg.protocol.Login.LoginRequest)
      }

      static {
        defaultInstance = new LoginRequest(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.server.msg.protocol.Login.LoginRequest)
    }

    public interface LoginResponseOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string userId = 2;
      /**
       * <code>optional string userId = 2;</code>
       */
      boolean hasUserId();
      /**
       * <code>optional string userId = 2;</code>
       */
      java.lang.String getUserId();
      /**
       * <code>optional string userId = 2;</code>
       */
      com.google.protobuf.ByteString
          getUserIdBytes();

      // optional string playerId = 3;
      /**
       * <code>optional string playerId = 3;</code>
       */
      boolean hasPlayerId();
      /**
       * <code>optional string playerId = 3;</code>
       */
      java.lang.String getPlayerId();
      /**
       * <code>optional string playerId = 3;</code>
       */
      com.google.protobuf.ByteString
          getPlayerIdBytes();

      // optional string name = 4;
      /**
       * <code>optional string name = 4;</code>
       */
      boolean hasName();
      /**
       * <code>optional string name = 4;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 4;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // optional int32 level = 5;
      /**
       * <code>optional int32 level = 5;</code>
       */
      boolean hasLevel();
      /**
       * <code>optional int32 level = 5;</code>
       */
      int getLevel();

      // optional int32 modelId = 6;
      /**
       * <code>optional int32 modelId = 6;</code>
       */
      boolean hasModelId();
      /**
       * <code>optional int32 modelId = 6;</code>
       */
      int getModelId();

      // optional .com.server.msg.protocol.Pos pos = 7;
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
       */
      boolean hasPos();
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
       */
      com.server.msg.protocol.Msg.Pos getPos();
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
       */
      com.server.msg.protocol.Msg.PosOrBuilder getPosOrBuilder();

      // optional int32 sceneId = 8;
      /**
       * <code>optional int32 sceneId = 8;</code>
       */
      boolean hasSceneId();
      /**
       * <code>optional int32 sceneId = 8;</code>
       */
      int getSceneId();
    }
    /**
     * Protobuf type {@code com.server.msg.protocol.Login.LoginResponse}
     */
    public static final class LoginResponse extends
        com.google.protobuf.GeneratedMessage
        implements LoginResponseOrBuilder {
      // Use LoginResponse.newBuilder() to construct.
      private LoginResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private LoginResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final LoginResponse defaultInstance;
      public static LoginResponse getDefaultInstance() {
        return defaultInstance;
      }

      public LoginResponse getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private LoginResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 18: {
                bitField0_ |= 0x00000001;
                userId_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000002;
                playerId_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000004;
                name_ = input.readBytes();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000008;
                level_ = input.readInt32();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000010;
                modelId_ = input.readInt32();
                break;
              }
              case 58: {
                com.server.msg.protocol.Msg.Pos.Builder subBuilder = null;
                if (((bitField0_ & 0x00000020) == 0x00000020)) {
                  subBuilder = pos_.toBuilder();
                }
                pos_ = input.readMessage(com.server.msg.protocol.Msg.Pos.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(pos_);
                  pos_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000020;
                break;
              }
              case 64: {
                bitField0_ |= 0x00000040;
                sceneId_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_LoginResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.msg.protocol.MsgLogin.Login.LoginResponse.class, com.server.msg.protocol.MsgLogin.Login.LoginResponse.Builder.class);
      }

      public static com.google.protobuf.Parser<LoginResponse> PARSER =
          new com.google.protobuf.AbstractParser<LoginResponse>() {
        public LoginResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoginResponse(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<LoginResponse> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string userId = 2;
      public static final int USERID_FIELD_NUMBER = 2;
      private java.lang.Object userId_;
      /**
       * <code>optional string userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string playerId = 3;
      public static final int PLAYERID_FIELD_NUMBER = 3;
      private java.lang.Object playerId_;
      /**
       * <code>optional string playerId = 3;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string playerId = 3;</code>
       */
      public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            playerId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string playerId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string name = 4;
      public static final int NAME_FIELD_NUMBER = 4;
      private java.lang.Object name_;
      /**
       * <code>optional string name = 4;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int32 level = 5;
      public static final int LEVEL_FIELD_NUMBER = 5;
      private int level_;
      /**
       * <code>optional int32 level = 5;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 level = 5;</code>
       */
      public int getLevel() {
        return level_;
      }

      // optional int32 modelId = 6;
      public static final int MODELID_FIELD_NUMBER = 6;
      private int modelId_;
      /**
       * <code>optional int32 modelId = 6;</code>
       */
      public boolean hasModelId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 modelId = 6;</code>
       */
      public int getModelId() {
        return modelId_;
      }

      // optional .com.server.msg.protocol.Pos pos = 7;
      public static final int POS_FIELD_NUMBER = 7;
      private com.server.msg.protocol.Msg.Pos pos_;
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
       */
      public boolean hasPos() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
       */
      public com.server.msg.protocol.Msg.Pos getPos() {
        return pos_;
      }
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
       */
      public com.server.msg.protocol.Msg.PosOrBuilder getPosOrBuilder() {
        return pos_;
      }

      // optional int32 sceneId = 8;
      public static final int SCENEID_FIELD_NUMBER = 8;
      private int sceneId_;
      /**
       * <code>optional int32 sceneId = 8;</code>
       */
      public boolean hasSceneId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 sceneId = 8;</code>
       */
      public int getSceneId() {
        return sceneId_;
      }

      private void initFields() {
        userId_ = "";
        playerId_ = "";
        name_ = "";
        level_ = 0;
        modelId_ = 0;
        pos_ = com.server.msg.protocol.Msg.Pos.getDefaultInstance();
        sceneId_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(2, getUserIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(3, getPlayerIdBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(4, getNameBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(5, level_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeInt32(6, modelId_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeMessage(7, pos_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeInt32(8, sceneId_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getUserIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getPlayerIdBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getNameBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, level_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, modelId_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, pos_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(8, sceneId_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.server.msg.protocol.MsgLogin.Login.LoginResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.msg.protocol.MsgLogin.Login.LoginResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.server.msg.protocol.MsgLogin.Login.LoginResponse prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.server.msg.protocol.Login.LoginResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.server.msg.protocol.MsgLogin.Login.LoginResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_LoginResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_LoginResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.server.msg.protocol.MsgLogin.Login.LoginResponse.class, com.server.msg.protocol.MsgLogin.Login.LoginResponse.Builder.class);
        }

        // Construct using com.server.msg.protocol.MsgLogin.Login.LoginResponse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getPosFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          userId_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          playerId_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          level_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          modelId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          if (posBuilder_ == null) {
            pos_ = com.server.msg.protocol.Msg.Pos.getDefaultInstance();
          } else {
            posBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000020);
          sceneId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000040);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_LoginResponse_descriptor;
        }

        public com.server.msg.protocol.MsgLogin.Login.LoginResponse getDefaultInstanceForType() {
          return com.server.msg.protocol.MsgLogin.Login.LoginResponse.getDefaultInstance();
        }

        public com.server.msg.protocol.MsgLogin.Login.LoginResponse build() {
          com.server.msg.protocol.MsgLogin.Login.LoginResponse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.server.msg.protocol.MsgLogin.Login.LoginResponse buildPartial() {
          com.server.msg.protocol.MsgLogin.Login.LoginResponse result = new com.server.msg.protocol.MsgLogin.Login.LoginResponse(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.userId_ = userId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.playerId_ = playerId_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.level_ = level_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.modelId_ = modelId_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          if (posBuilder_ == null) {
            result.pos_ = pos_;
          } else {
            result.pos_ = posBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.sceneId_ = sceneId_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.server.msg.protocol.MsgLogin.Login.LoginResponse) {
            return mergeFrom((com.server.msg.protocol.MsgLogin.Login.LoginResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.server.msg.protocol.MsgLogin.Login.LoginResponse other) {
          if (other == com.server.msg.protocol.MsgLogin.Login.LoginResponse.getDefaultInstance()) return this;
          if (other.hasUserId()) {
            bitField0_ |= 0x00000001;
            userId_ = other.userId_;
            onChanged();
          }
          if (other.hasPlayerId()) {
            bitField0_ |= 0x00000002;
            playerId_ = other.playerId_;
            onChanged();
          }
          if (other.hasName()) {
            bitField0_ |= 0x00000004;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasLevel()) {
            setLevel(other.getLevel());
          }
          if (other.hasModelId()) {
            setModelId(other.getModelId());
          }
          if (other.hasPos()) {
            mergePos(other.getPos());
          }
          if (other.hasSceneId()) {
            setSceneId(other.getSceneId());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.server.msg.protocol.MsgLogin.Login.LoginResponse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.server.msg.protocol.MsgLogin.Login.LoginResponse) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string userId = 2;
        private java.lang.Object userId_ = "";
        /**
         * <code>optional string userId = 2;</code>
         */
        public boolean hasUserId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string userId = 2;</code>
         */
        public java.lang.String getUserId() {
          java.lang.Object ref = userId_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            userId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string userId = 2;</code>
         */
        public com.google.protobuf.ByteString
            getUserIdBytes() {
          java.lang.Object ref = userId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            userId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string userId = 2;</code>
         */
        public Builder setUserId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          userId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string userId = 2;</code>
         */
        public Builder clearUserId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          userId_ = getDefaultInstance().getUserId();
          onChanged();
          return this;
        }
        /**
         * <code>optional string userId = 2;</code>
         */
        public Builder setUserIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          userId_ = value;
          onChanged();
          return this;
        }

        // optional string playerId = 3;
        private java.lang.Object playerId_ = "";
        /**
         * <code>optional string playerId = 3;</code>
         */
        public boolean hasPlayerId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string playerId = 3;</code>
         */
        public java.lang.String getPlayerId() {
          java.lang.Object ref = playerId_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            playerId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string playerId = 3;</code>
         */
        public com.google.protobuf.ByteString
            getPlayerIdBytes() {
          java.lang.Object ref = playerId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            playerId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string playerId = 3;</code>
         */
        public Builder setPlayerId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          playerId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string playerId = 3;</code>
         */
        public Builder clearPlayerId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          playerId_ = getDefaultInstance().getPlayerId();
          onChanged();
          return this;
        }
        /**
         * <code>optional string playerId = 3;</code>
         */
        public Builder setPlayerIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          playerId_ = value;
          onChanged();
          return this;
        }

        // optional string name = 4;
        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 4;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string name = 4;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 4;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 4;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 4;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000004);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 4;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
          return this;
        }

        // optional int32 level = 5;
        private int level_ ;
        /**
         * <code>optional int32 level = 5;</code>
         */
        public boolean hasLevel() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int32 level = 5;</code>
         */
        public int getLevel() {
          return level_;
        }
        /**
         * <code>optional int32 level = 5;</code>
         */
        public Builder setLevel(int value) {
          bitField0_ |= 0x00000008;
          level_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 level = 5;</code>
         */
        public Builder clearLevel() {
          bitField0_ = (bitField0_ & ~0x00000008);
          level_ = 0;
          onChanged();
          return this;
        }

        // optional int32 modelId = 6;
        private int modelId_ ;
        /**
         * <code>optional int32 modelId = 6;</code>
         */
        public boolean hasModelId() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional int32 modelId = 6;</code>
         */
        public int getModelId() {
          return modelId_;
        }
        /**
         * <code>optional int32 modelId = 6;</code>
         */
        public Builder setModelId(int value) {
          bitField0_ |= 0x00000010;
          modelId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 modelId = 6;</code>
         */
        public Builder clearModelId() {
          bitField0_ = (bitField0_ & ~0x00000010);
          modelId_ = 0;
          onChanged();
          return this;
        }

        // optional .com.server.msg.protocol.Pos pos = 7;
        private com.server.msg.protocol.Msg.Pos pos_ = com.server.msg.protocol.Msg.Pos.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.server.msg.protocol.Msg.Pos, com.server.msg.protocol.Msg.Pos.Builder, com.server.msg.protocol.Msg.PosOrBuilder> posBuilder_;
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
         */
        public boolean hasPos() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
         */
        public com.server.msg.protocol.Msg.Pos getPos() {
          if (posBuilder_ == null) {
            return pos_;
          } else {
            return posBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
         */
        public Builder setPos(com.server.msg.protocol.Msg.Pos value) {
          if (posBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            pos_ = value;
            onChanged();
          } else {
            posBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000020;
          return this;
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
         */
        public Builder setPos(
            com.server.msg.protocol.Msg.Pos.Builder builderForValue) {
          if (posBuilder_ == null) {
            pos_ = builderForValue.build();
            onChanged();
          } else {
            posBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000020;
          return this;
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
         */
        public Builder mergePos(com.server.msg.protocol.Msg.Pos value) {
          if (posBuilder_ == null) {
            if (((bitField0_ & 0x00000020) == 0x00000020) &&
                pos_ != com.server.msg.protocol.Msg.Pos.getDefaultInstance()) {
              pos_ =
                com.server.msg.protocol.Msg.Pos.newBuilder(pos_).mergeFrom(value).buildPartial();
            } else {
              pos_ = value;
            }
            onChanged();
          } else {
            posBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000020;
          return this;
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
         */
        public Builder clearPos() {
          if (posBuilder_ == null) {
            pos_ = com.server.msg.protocol.Msg.Pos.getDefaultInstance();
            onChanged();
          } else {
            posBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
         */
        public com.server.msg.protocol.Msg.Pos.Builder getPosBuilder() {
          bitField0_ |= 0x00000020;
          onChanged();
          return getPosFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
         */
        public com.server.msg.protocol.Msg.PosOrBuilder getPosOrBuilder() {
          if (posBuilder_ != null) {
            return posBuilder_.getMessageOrBuilder();
          } else {
            return pos_;
          }
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 7;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            com.server.msg.protocol.Msg.Pos, com.server.msg.protocol.Msg.Pos.Builder, com.server.msg.protocol.Msg.PosOrBuilder> 
            getPosFieldBuilder() {
          if (posBuilder_ == null) {
            posBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.server.msg.protocol.Msg.Pos, com.server.msg.protocol.Msg.Pos.Builder, com.server.msg.protocol.Msg.PosOrBuilder>(
                    pos_,
                    getParentForChildren(),
                    isClean());
            pos_ = null;
          }
          return posBuilder_;
        }

        // optional int32 sceneId = 8;
        private int sceneId_ ;
        /**
         * <code>optional int32 sceneId = 8;</code>
         */
        public boolean hasSceneId() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional int32 sceneId = 8;</code>
         */
        public int getSceneId() {
          return sceneId_;
        }
        /**
         * <code>optional int32 sceneId = 8;</code>
         */
        public Builder setSceneId(int value) {
          bitField0_ |= 0x00000040;
          sceneId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 sceneId = 8;</code>
         */
        public Builder clearSceneId() {
          bitField0_ = (bitField0_ & ~0x00000040);
          sceneId_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.server.msg.protocol.Login.LoginResponse)
      }

      static {
        defaultInstance = new LoginResponse(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.server.msg.protocol.Login.LoginResponse)
    }

    private int bitField0_;
    // optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;
    public static final int LOGINREQUEST_FIELD_NUMBER = 1;
    private com.server.msg.protocol.MsgLogin.Login.LoginRequest loginRequest_;
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
     */
    public boolean hasLoginRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
     */
    public com.server.msg.protocol.MsgLogin.Login.LoginRequest getLoginRequest() {
      return loginRequest_;
    }
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
     */
    public com.server.msg.protocol.MsgLogin.Login.LoginRequestOrBuilder getLoginRequestOrBuilder() {
      return loginRequest_;
    }

    // optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;
    public static final int LOGINRESPONSE_FIELD_NUMBER = 2;
    private com.server.msg.protocol.MsgLogin.Login.LoginResponse loginResponse_;
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
     */
    public boolean hasLoginResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
     */
    public com.server.msg.protocol.MsgLogin.Login.LoginResponse getLoginResponse() {
      return loginResponse_;
    }
    /**
     * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
     */
    public com.server.msg.protocol.MsgLogin.Login.LoginResponseOrBuilder getLoginResponseOrBuilder() {
      return loginResponse_;
    }

    private void initFields() {
      loginRequest_ = com.server.msg.protocol.MsgLogin.Login.LoginRequest.getDefaultInstance();
      loginResponse_ = com.server.msg.protocol.MsgLogin.Login.LoginResponse.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, loginRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, loginResponse_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, loginRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, loginResponse_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.server.msg.protocol.MsgLogin.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.msg.protocol.MsgLogin.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.msg.protocol.MsgLogin.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.msg.protocol.MsgLogin.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.msg.protocol.MsgLogin.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.msg.protocol.MsgLogin.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.server.msg.protocol.MsgLogin.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.server.msg.protocol.MsgLogin.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.server.msg.protocol.MsgLogin.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.msg.protocol.MsgLogin.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.server.msg.protocol.MsgLogin.Login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.server.msg.protocol.Login}
     *
     * <pre>
     *登录模块
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.server.msg.protocol.MsgLogin.LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.msg.protocol.MsgLogin.Login.class, com.server.msg.protocol.MsgLogin.Login.Builder.class);
      }

      // Construct using com.server.msg.protocol.MsgLogin.Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLoginRequestFieldBuilder();
          getLoginResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (loginRequestBuilder_ == null) {
          loginRequest_ = com.server.msg.protocol.MsgLogin.Login.LoginRequest.getDefaultInstance();
        } else {
          loginRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (loginResponseBuilder_ == null) {
          loginResponse_ = com.server.msg.protocol.MsgLogin.Login.LoginResponse.getDefaultInstance();
        } else {
          loginResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.msg.protocol.MsgLogin.internal_static_com_server_msg_protocol_Login_descriptor;
      }

      public com.server.msg.protocol.MsgLogin.Login getDefaultInstanceForType() {
        return com.server.msg.protocol.MsgLogin.Login.getDefaultInstance();
      }

      public com.server.msg.protocol.MsgLogin.Login build() {
        com.server.msg.protocol.MsgLogin.Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.server.msg.protocol.MsgLogin.Login buildPartial() {
        com.server.msg.protocol.MsgLogin.Login result = new com.server.msg.protocol.MsgLogin.Login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (loginRequestBuilder_ == null) {
          result.loginRequest_ = loginRequest_;
        } else {
          result.loginRequest_ = loginRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (loginResponseBuilder_ == null) {
          result.loginResponse_ = loginResponse_;
        } else {
          result.loginResponse_ = loginResponseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.msg.protocol.MsgLogin.Login) {
          return mergeFrom((com.server.msg.protocol.MsgLogin.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.msg.protocol.MsgLogin.Login other) {
        if (other == com.server.msg.protocol.MsgLogin.Login.getDefaultInstance()) return this;
        if (other.hasLoginRequest()) {
          mergeLoginRequest(other.getLoginRequest());
        }
        if (other.hasLoginResponse()) {
          mergeLoginResponse(other.getLoginResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.msg.protocol.MsgLogin.Login parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.msg.protocol.MsgLogin.Login) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;
      private com.server.msg.protocol.MsgLogin.Login.LoginRequest loginRequest_ = com.server.msg.protocol.MsgLogin.Login.LoginRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.server.msg.protocol.MsgLogin.Login.LoginRequest, com.server.msg.protocol.MsgLogin.Login.LoginRequest.Builder, com.server.msg.protocol.MsgLogin.Login.LoginRequestOrBuilder> loginRequestBuilder_;
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
       */
      public boolean hasLoginRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
       */
      public com.server.msg.protocol.MsgLogin.Login.LoginRequest getLoginRequest() {
        if (loginRequestBuilder_ == null) {
          return loginRequest_;
        } else {
          return loginRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
       */
      public Builder setLoginRequest(com.server.msg.protocol.MsgLogin.Login.LoginRequest value) {
        if (loginRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loginRequest_ = value;
          onChanged();
        } else {
          loginRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
       */
      public Builder setLoginRequest(
          com.server.msg.protocol.MsgLogin.Login.LoginRequest.Builder builderForValue) {
        if (loginRequestBuilder_ == null) {
          loginRequest_ = builderForValue.build();
          onChanged();
        } else {
          loginRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
       */
      public Builder mergeLoginRequest(com.server.msg.protocol.MsgLogin.Login.LoginRequest value) {
        if (loginRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              loginRequest_ != com.server.msg.protocol.MsgLogin.Login.LoginRequest.getDefaultInstance()) {
            loginRequest_ =
              com.server.msg.protocol.MsgLogin.Login.LoginRequest.newBuilder(loginRequest_).mergeFrom(value).buildPartial();
          } else {
            loginRequest_ = value;
          }
          onChanged();
        } else {
          loginRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
       */
      public Builder clearLoginRequest() {
        if (loginRequestBuilder_ == null) {
          loginRequest_ = com.server.msg.protocol.MsgLogin.Login.LoginRequest.getDefaultInstance();
          onChanged();
        } else {
          loginRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
       */
      public com.server.msg.protocol.MsgLogin.Login.LoginRequest.Builder getLoginRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getLoginRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
       */
      public com.server.msg.protocol.MsgLogin.Login.LoginRequestOrBuilder getLoginRequestOrBuilder() {
        if (loginRequestBuilder_ != null) {
          return loginRequestBuilder_.getMessageOrBuilder();
        } else {
          return loginRequest_;
        }
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginRequest loginRequest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.server.msg.protocol.MsgLogin.Login.LoginRequest, com.server.msg.protocol.MsgLogin.Login.LoginRequest.Builder, com.server.msg.protocol.MsgLogin.Login.LoginRequestOrBuilder> 
          getLoginRequestFieldBuilder() {
        if (loginRequestBuilder_ == null) {
          loginRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.server.msg.protocol.MsgLogin.Login.LoginRequest, com.server.msg.protocol.MsgLogin.Login.LoginRequest.Builder, com.server.msg.protocol.MsgLogin.Login.LoginRequestOrBuilder>(
                  loginRequest_,
                  getParentForChildren(),
                  isClean());
          loginRequest_ = null;
        }
        return loginRequestBuilder_;
      }

      // optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;
      private com.server.msg.protocol.MsgLogin.Login.LoginResponse loginResponse_ = com.server.msg.protocol.MsgLogin.Login.LoginResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.server.msg.protocol.MsgLogin.Login.LoginResponse, com.server.msg.protocol.MsgLogin.Login.LoginResponse.Builder, com.server.msg.protocol.MsgLogin.Login.LoginResponseOrBuilder> loginResponseBuilder_;
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
       */
      public boolean hasLoginResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
       */
      public com.server.msg.protocol.MsgLogin.Login.LoginResponse getLoginResponse() {
        if (loginResponseBuilder_ == null) {
          return loginResponse_;
        } else {
          return loginResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
       */
      public Builder setLoginResponse(com.server.msg.protocol.MsgLogin.Login.LoginResponse value) {
        if (loginResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loginResponse_ = value;
          onChanged();
        } else {
          loginResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
       */
      public Builder setLoginResponse(
          com.server.msg.protocol.MsgLogin.Login.LoginResponse.Builder builderForValue) {
        if (loginResponseBuilder_ == null) {
          loginResponse_ = builderForValue.build();
          onChanged();
        } else {
          loginResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
       */
      public Builder mergeLoginResponse(com.server.msg.protocol.MsgLogin.Login.LoginResponse value) {
        if (loginResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              loginResponse_ != com.server.msg.protocol.MsgLogin.Login.LoginResponse.getDefaultInstance()) {
            loginResponse_ =
              com.server.msg.protocol.MsgLogin.Login.LoginResponse.newBuilder(loginResponse_).mergeFrom(value).buildPartial();
          } else {
            loginResponse_ = value;
          }
          onChanged();
        } else {
          loginResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
       */
      public Builder clearLoginResponse() {
        if (loginResponseBuilder_ == null) {
          loginResponse_ = com.server.msg.protocol.MsgLogin.Login.LoginResponse.getDefaultInstance();
          onChanged();
        } else {
          loginResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
       */
      public com.server.msg.protocol.MsgLogin.Login.LoginResponse.Builder getLoginResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLoginResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
       */
      public com.server.msg.protocol.MsgLogin.Login.LoginResponseOrBuilder getLoginResponseOrBuilder() {
        if (loginResponseBuilder_ != null) {
          return loginResponseBuilder_.getMessageOrBuilder();
        } else {
          return loginResponse_;
        }
      }
      /**
       * <code>optional .com.server.msg.protocol.Login.LoginResponse loginResponse = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.server.msg.protocol.MsgLogin.Login.LoginResponse, com.server.msg.protocol.MsgLogin.Login.LoginResponse.Builder, com.server.msg.protocol.MsgLogin.Login.LoginResponseOrBuilder> 
          getLoginResponseFieldBuilder() {
        if (loginResponseBuilder_ == null) {
          loginResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.server.msg.protocol.MsgLogin.Login.LoginResponse, com.server.msg.protocol.MsgLogin.Login.LoginResponse.Builder, com.server.msg.protocol.MsgLogin.Login.LoginResponseOrBuilder>(
                  loginResponse_,
                  getParentForChildren(),
                  isClean());
          loginResponse_ = null;
        }
        return loginResponseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.server.msg.protocol.Login)
    }

    static {
      defaultInstance = new Login(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.server.msg.protocol.Login)
  }

  public static final int LOGIN_FIELD_NUMBER = 100;
  /**
   * <code>extend .com.server.msg.protocol.Message { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.server.msg.protocol.Msg.Message,
      com.server.msg.protocol.MsgLogin.Login> login = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.server.msg.protocol.MsgLogin.Login.class,
        com.server.msg.protocol.MsgLogin.Login.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_server_msg_protocol_Login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_server_msg_protocol_Login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_server_msg_protocol_Login_LoginRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_server_msg_protocol_Login_LoginRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_server_msg_protocol_Login_LoginResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_server_msg_protocol_Login_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017msg_login.proto\022\027com.server.msg.protoc" +
      "ol\032\tmsg.proto\"\333\002\n\005Login\022A\n\014loginRequest\030" +
      "\001 \001(\0132+.com.server.msg.protocol.Login.Lo" +
      "ginRequest\022C\n\rloginResponse\030\002 \001(\0132,.com." +
      "server.msg.protocol.Login.LoginResponse\032" +
      "%\n\014LoginRequest\022\016\n\006userId\030\002 \001(\t:\005\220\202\031\350\007\032\242" +
      "\001\n\rLoginResponse\022\016\n\006userId\030\002 \001(\t\022\020\n\010play" +
      "erId\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\r\n\005level\030\005 \001(\005\022" +
      "\017\n\007modelId\030\006 \001(\005\022)\n\003pos\030\007 \001(\0132\034.com.serv" +
      "er.msg.protocol.Pos\022\017\n\007sceneId\030\010 \001(\005:\005\220\202",
      "\031\351\007:O\n\005login\022 .com.server.msg.protocol.M" +
      "essage\030d \001(\0132\036.com.server.msg.protocol.L" +
      "ogin"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_server_msg_protocol_Login_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_server_msg_protocol_Login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_server_msg_protocol_Login_descriptor,
              new java.lang.String[] { "LoginRequest", "LoginResponse", });
          internal_static_com_server_msg_protocol_Login_LoginRequest_descriptor =
            internal_static_com_server_msg_protocol_Login_descriptor.getNestedTypes().get(0);
          internal_static_com_server_msg_protocol_Login_LoginRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_server_msg_protocol_Login_LoginRequest_descriptor,
              new java.lang.String[] { "UserId", });
          internal_static_com_server_msg_protocol_Login_LoginResponse_descriptor =
            internal_static_com_server_msg_protocol_Login_descriptor.getNestedTypes().get(1);
          internal_static_com_server_msg_protocol_Login_LoginResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_server_msg_protocol_Login_LoginResponse_descriptor,
              new java.lang.String[] { "UserId", "PlayerId", "Name", "Level", "ModelId", "Pos", "SceneId", });
          login.internalInit(descriptor.getExtensions().get(0));
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(com.server.msg.protocol.Msg.msgId);
          registry.add(com.server.msg.protocol.Msg.msgId);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.server.msg.protocol.Msg.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
