// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_map.proto

package com.server.msg.protocol;

public final class MsgMap {
  private MsgMap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.server.msg.protocol.MsgMap.map);
  }
  public interface MapOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
     */
    boolean hasEnterSceneRequest();
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
     */
    com.server.msg.protocol.MsgMap.Map.EnterSceneRequest getEnterSceneRequest();
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
     */
    com.server.msg.protocol.MsgMap.Map.EnterSceneRequestOrBuilder getEnterSceneRequestOrBuilder();

    // optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
     */
    boolean hasEnterSceneResPonse();
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
     */
    com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse getEnterSceneResPonse();
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
     */
    com.server.msg.protocol.MsgMap.Map.EnterSceneResPonseOrBuilder getEnterSceneResPonseOrBuilder();

    // optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;
    /**
     * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
     */
    boolean hasLoadComplete();
    /**
     * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
     */
    com.server.msg.protocol.MsgMap.Map.LoadComplete getLoadComplete();
    /**
     * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
     */
    com.server.msg.protocol.MsgMap.Map.LoadCompleteOrBuilder getLoadCompleteOrBuilder();
  }
  /**
   * Protobuf type {@code com.server.msg.protocol.Map}
   *
   * <pre>
   *地图模块
   * </pre>
   */
  public static final class Map extends
      com.google.protobuf.GeneratedMessage
      implements MapOrBuilder {
    // Use Map.newBuilder() to construct.
    private Map(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Map(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Map defaultInstance;
    public static Map getDefaultInstance() {
      return defaultInstance;
    }

    public Map getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Map(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = enterSceneRequest_.toBuilder();
              }
              enterSceneRequest_ = input.readMessage(com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(enterSceneRequest_);
                enterSceneRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = enterSceneResPonse_.toBuilder();
              }
              enterSceneResPonse_ = input.readMessage(com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(enterSceneResPonse_);
                enterSceneResPonse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.server.msg.protocol.MsgMap.Map.LoadComplete.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = loadComplete_.toBuilder();
              }
              loadComplete_ = input.readMessage(com.server.msg.protocol.MsgMap.Map.LoadComplete.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(loadComplete_);
                loadComplete_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.msg.protocol.MsgMap.Map.class, com.server.msg.protocol.MsgMap.Map.Builder.class);
    }

    public static com.google.protobuf.Parser<Map> PARSER =
        new com.google.protobuf.AbstractParser<Map>() {
      public Map parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Map(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Map> getParserForType() {
      return PARSER;
    }

    public interface EnterSceneRequestOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional int32 sceneId = 2;
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      boolean hasSceneId();
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      int getSceneId();
    }
    /**
     * Protobuf type {@code com.server.msg.protocol.Map.EnterSceneRequest}
     */
    public static final class EnterSceneRequest extends
        com.google.protobuf.GeneratedMessage
        implements EnterSceneRequestOrBuilder {
      // Use EnterSceneRequest.newBuilder() to construct.
      private EnterSceneRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private EnterSceneRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final EnterSceneRequest defaultInstance;
      public static EnterSceneRequest getDefaultInstance() {
        return defaultInstance;
      }

      public EnterSceneRequest getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private EnterSceneRequest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 16: {
                bitField0_ |= 0x00000001;
                sceneId_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_EnterSceneRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_EnterSceneRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.class, com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.Builder.class);
      }

      public static com.google.protobuf.Parser<EnterSceneRequest> PARSER =
          new com.google.protobuf.AbstractParser<EnterSceneRequest>() {
        public EnterSceneRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new EnterSceneRequest(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<EnterSceneRequest> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional int32 sceneId = 2;
      public static final int SCENEID_FIELD_NUMBER = 2;
      private int sceneId_;
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      public boolean hasSceneId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      public int getSceneId() {
        return sceneId_;
      }

      private void initFields() {
        sceneId_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(2, sceneId_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, sceneId_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.server.msg.protocol.MsgMap.Map.EnterSceneRequest prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.server.msg.protocol.Map.EnterSceneRequest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.server.msg.protocol.MsgMap.Map.EnterSceneRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_EnterSceneRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_EnterSceneRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.class, com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.Builder.class);
        }

        // Construct using com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          sceneId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_EnterSceneRequest_descriptor;
        }

        public com.server.msg.protocol.MsgMap.Map.EnterSceneRequest getDefaultInstanceForType() {
          return com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.getDefaultInstance();
        }

        public com.server.msg.protocol.MsgMap.Map.EnterSceneRequest build() {
          com.server.msg.protocol.MsgMap.Map.EnterSceneRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.server.msg.protocol.MsgMap.Map.EnterSceneRequest buildPartial() {
          com.server.msg.protocol.MsgMap.Map.EnterSceneRequest result = new com.server.msg.protocol.MsgMap.Map.EnterSceneRequest(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.sceneId_ = sceneId_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.server.msg.protocol.MsgMap.Map.EnterSceneRequest) {
            return mergeFrom((com.server.msg.protocol.MsgMap.Map.EnterSceneRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.server.msg.protocol.MsgMap.Map.EnterSceneRequest other) {
          if (other == com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.getDefaultInstance()) return this;
          if (other.hasSceneId()) {
            setSceneId(other.getSceneId());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.server.msg.protocol.MsgMap.Map.EnterSceneRequest parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.server.msg.protocol.MsgMap.Map.EnterSceneRequest) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional int32 sceneId = 2;
        private int sceneId_ ;
        /**
         * <code>optional int32 sceneId = 2;</code>
         */
        public boolean hasSceneId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 sceneId = 2;</code>
         */
        public int getSceneId() {
          return sceneId_;
        }
        /**
         * <code>optional int32 sceneId = 2;</code>
         */
        public Builder setSceneId(int value) {
          bitField0_ |= 0x00000001;
          sceneId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 sceneId = 2;</code>
         */
        public Builder clearSceneId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          sceneId_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.server.msg.protocol.Map.EnterSceneRequest)
      }

      static {
        defaultInstance = new EnterSceneRequest(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.server.msg.protocol.Map.EnterSceneRequest)
    }

    public interface EnterSceneResPonseOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional .com.server.msg.protocol.Pos pos = 2;
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
       */
      boolean hasPos();
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
       */
      com.server.msg.protocol.Msg.Pos getPos();
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
       */
      com.server.msg.protocol.Msg.PosOrBuilder getPosOrBuilder();
    }
    /**
     * Protobuf type {@code com.server.msg.protocol.Map.EnterSceneResPonse}
     */
    public static final class EnterSceneResPonse extends
        com.google.protobuf.GeneratedMessage
        implements EnterSceneResPonseOrBuilder {
      // Use EnterSceneResPonse.newBuilder() to construct.
      private EnterSceneResPonse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private EnterSceneResPonse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final EnterSceneResPonse defaultInstance;
      public static EnterSceneResPonse getDefaultInstance() {
        return defaultInstance;
      }

      public EnterSceneResPonse getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private EnterSceneResPonse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 18: {
                com.server.msg.protocol.Msg.Pos.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = pos_.toBuilder();
                }
                pos_ = input.readMessage(com.server.msg.protocol.Msg.Pos.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(pos_);
                  pos_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_EnterSceneResPonse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_EnterSceneResPonse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.class, com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.Builder.class);
      }

      public static com.google.protobuf.Parser<EnterSceneResPonse> PARSER =
          new com.google.protobuf.AbstractParser<EnterSceneResPonse>() {
        public EnterSceneResPonse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new EnterSceneResPonse(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<EnterSceneResPonse> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional .com.server.msg.protocol.Pos pos = 2;
      public static final int POS_FIELD_NUMBER = 2;
      private com.server.msg.protocol.Msg.Pos pos_;
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
       */
      public boolean hasPos() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
       */
      public com.server.msg.protocol.Msg.Pos getPos() {
        return pos_;
      }
      /**
       * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
       */
      public com.server.msg.protocol.Msg.PosOrBuilder getPosOrBuilder() {
        return pos_;
      }

      private void initFields() {
        pos_ = com.server.msg.protocol.Msg.Pos.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeMessage(2, pos_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, pos_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.server.msg.protocol.Map.EnterSceneResPonse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.server.msg.protocol.MsgMap.Map.EnterSceneResPonseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_EnterSceneResPonse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_EnterSceneResPonse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.class, com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.Builder.class);
        }

        // Construct using com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getPosFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          if (posBuilder_ == null) {
            pos_ = com.server.msg.protocol.Msg.Pos.getDefaultInstance();
          } else {
            posBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_EnterSceneResPonse_descriptor;
        }

        public com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse getDefaultInstanceForType() {
          return com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.getDefaultInstance();
        }

        public com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse build() {
          com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse buildPartial() {
          com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse result = new com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          if (posBuilder_ == null) {
            result.pos_ = pos_;
          } else {
            result.pos_ = posBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse) {
            return mergeFrom((com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse other) {
          if (other == com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.getDefaultInstance()) return this;
          if (other.hasPos()) {
            mergePos(other.getPos());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional .com.server.msg.protocol.Pos pos = 2;
        private com.server.msg.protocol.Msg.Pos pos_ = com.server.msg.protocol.Msg.Pos.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.server.msg.protocol.Msg.Pos, com.server.msg.protocol.Msg.Pos.Builder, com.server.msg.protocol.Msg.PosOrBuilder> posBuilder_;
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
         */
        public boolean hasPos() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
         */
        public com.server.msg.protocol.Msg.Pos getPos() {
          if (posBuilder_ == null) {
            return pos_;
          } else {
            return posBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
         */
        public Builder setPos(com.server.msg.protocol.Msg.Pos value) {
          if (posBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            pos_ = value;
            onChanged();
          } else {
            posBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
         */
        public Builder setPos(
            com.server.msg.protocol.Msg.Pos.Builder builderForValue) {
          if (posBuilder_ == null) {
            pos_ = builderForValue.build();
            onChanged();
          } else {
            posBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
         */
        public Builder mergePos(com.server.msg.protocol.Msg.Pos value) {
          if (posBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                pos_ != com.server.msg.protocol.Msg.Pos.getDefaultInstance()) {
              pos_ =
                com.server.msg.protocol.Msg.Pos.newBuilder(pos_).mergeFrom(value).buildPartial();
            } else {
              pos_ = value;
            }
            onChanged();
          } else {
            posBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
         */
        public Builder clearPos() {
          if (posBuilder_ == null) {
            pos_ = com.server.msg.protocol.Msg.Pos.getDefaultInstance();
            onChanged();
          } else {
            posBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
         */
        public com.server.msg.protocol.Msg.Pos.Builder getPosBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getPosFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
         */
        public com.server.msg.protocol.Msg.PosOrBuilder getPosOrBuilder() {
          if (posBuilder_ != null) {
            return posBuilder_.getMessageOrBuilder();
          } else {
            return pos_;
          }
        }
        /**
         * <code>optional .com.server.msg.protocol.Pos pos = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            com.server.msg.protocol.Msg.Pos, com.server.msg.protocol.Msg.Pos.Builder, com.server.msg.protocol.Msg.PosOrBuilder> 
            getPosFieldBuilder() {
          if (posBuilder_ == null) {
            posBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.server.msg.protocol.Msg.Pos, com.server.msg.protocol.Msg.Pos.Builder, com.server.msg.protocol.Msg.PosOrBuilder>(
                    pos_,
                    getParentForChildren(),
                    isClean());
            pos_ = null;
          }
          return posBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:com.server.msg.protocol.Map.EnterSceneResPonse)
      }

      static {
        defaultInstance = new EnterSceneResPonse(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.server.msg.protocol.Map.EnterSceneResPonse)
    }

    public interface LoadCompleteOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code com.server.msg.protocol.Map.LoadComplete}
     *
     * <pre>
     *地图加载(过图中不发送数据，加载完成再发送数据)
     * </pre>
     */
    public static final class LoadComplete extends
        com.google.protobuf.GeneratedMessage
        implements LoadCompleteOrBuilder {
      // Use LoadComplete.newBuilder() to construct.
      private LoadComplete(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private LoadComplete(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final LoadComplete defaultInstance;
      public static LoadComplete getDefaultInstance() {
        return defaultInstance;
      }

      public LoadComplete getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private LoadComplete(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_LoadComplete_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_LoadComplete_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.msg.protocol.MsgMap.Map.LoadComplete.class, com.server.msg.protocol.MsgMap.Map.LoadComplete.Builder.class);
      }

      public static com.google.protobuf.Parser<LoadComplete> PARSER =
          new com.google.protobuf.AbstractParser<LoadComplete>() {
        public LoadComplete parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LoadComplete(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<LoadComplete> getParserForType() {
        return PARSER;
      }

      private void initFields() {
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.server.msg.protocol.MsgMap.Map.LoadComplete parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.msg.protocol.MsgMap.Map.LoadComplete parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.LoadComplete parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.server.msg.protocol.MsgMap.Map.LoadComplete parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.LoadComplete parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.msg.protocol.MsgMap.Map.LoadComplete parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.LoadComplete parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.server.msg.protocol.MsgMap.Map.LoadComplete parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.server.msg.protocol.MsgMap.Map.LoadComplete parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.server.msg.protocol.MsgMap.Map.LoadComplete parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.server.msg.protocol.MsgMap.Map.LoadComplete prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.server.msg.protocol.Map.LoadComplete}
       *
       * <pre>
       *地图加载(过图中不发送数据，加载完成再发送数据)
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.server.msg.protocol.MsgMap.Map.LoadCompleteOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_LoadComplete_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_LoadComplete_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.server.msg.protocol.MsgMap.Map.LoadComplete.class, com.server.msg.protocol.MsgMap.Map.LoadComplete.Builder.class);
        }

        // Construct using com.server.msg.protocol.MsgMap.Map.LoadComplete.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_LoadComplete_descriptor;
        }

        public com.server.msg.protocol.MsgMap.Map.LoadComplete getDefaultInstanceForType() {
          return com.server.msg.protocol.MsgMap.Map.LoadComplete.getDefaultInstance();
        }

        public com.server.msg.protocol.MsgMap.Map.LoadComplete build() {
          com.server.msg.protocol.MsgMap.Map.LoadComplete result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.server.msg.protocol.MsgMap.Map.LoadComplete buildPartial() {
          com.server.msg.protocol.MsgMap.Map.LoadComplete result = new com.server.msg.protocol.MsgMap.Map.LoadComplete(this);
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.server.msg.protocol.MsgMap.Map.LoadComplete) {
            return mergeFrom((com.server.msg.protocol.MsgMap.Map.LoadComplete)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.server.msg.protocol.MsgMap.Map.LoadComplete other) {
          if (other == com.server.msg.protocol.MsgMap.Map.LoadComplete.getDefaultInstance()) return this;
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.server.msg.protocol.MsgMap.Map.LoadComplete parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.server.msg.protocol.MsgMap.Map.LoadComplete) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.server.msg.protocol.Map.LoadComplete)
      }

      static {
        defaultInstance = new LoadComplete(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.server.msg.protocol.Map.LoadComplete)
    }

    private int bitField0_;
    // optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;
    public static final int ENTERSCENEREQUEST_FIELD_NUMBER = 1;
    private com.server.msg.protocol.MsgMap.Map.EnterSceneRequest enterSceneRequest_;
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
     */
    public boolean hasEnterSceneRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
     */
    public com.server.msg.protocol.MsgMap.Map.EnterSceneRequest getEnterSceneRequest() {
      return enterSceneRequest_;
    }
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
     */
    public com.server.msg.protocol.MsgMap.Map.EnterSceneRequestOrBuilder getEnterSceneRequestOrBuilder() {
      return enterSceneRequest_;
    }

    // optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;
    public static final int ENTERSCENERESPONSE_FIELD_NUMBER = 2;
    private com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse enterSceneResPonse_;
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
     */
    public boolean hasEnterSceneResPonse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
     */
    public com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse getEnterSceneResPonse() {
      return enterSceneResPonse_;
    }
    /**
     * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
     */
    public com.server.msg.protocol.MsgMap.Map.EnterSceneResPonseOrBuilder getEnterSceneResPonseOrBuilder() {
      return enterSceneResPonse_;
    }

    // optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;
    public static final int LOADCOMPLETE_FIELD_NUMBER = 3;
    private com.server.msg.protocol.MsgMap.Map.LoadComplete loadComplete_;
    /**
     * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
     */
    public boolean hasLoadComplete() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
     */
    public com.server.msg.protocol.MsgMap.Map.LoadComplete getLoadComplete() {
      return loadComplete_;
    }
    /**
     * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
     */
    public com.server.msg.protocol.MsgMap.Map.LoadCompleteOrBuilder getLoadCompleteOrBuilder() {
      return loadComplete_;
    }

    private void initFields() {
      enterSceneRequest_ = com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.getDefaultInstance();
      enterSceneResPonse_ = com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.getDefaultInstance();
      loadComplete_ = com.server.msg.protocol.MsgMap.Map.LoadComplete.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, enterSceneRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, enterSceneResPonse_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, loadComplete_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, enterSceneRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, enterSceneResPonse_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, loadComplete_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.server.msg.protocol.MsgMap.Map parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.msg.protocol.MsgMap.Map parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.msg.protocol.MsgMap.Map parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.msg.protocol.MsgMap.Map parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.msg.protocol.MsgMap.Map parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.msg.protocol.MsgMap.Map parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.server.msg.protocol.MsgMap.Map parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.server.msg.protocol.MsgMap.Map parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.server.msg.protocol.MsgMap.Map parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.msg.protocol.MsgMap.Map parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.server.msg.protocol.MsgMap.Map prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.server.msg.protocol.Map}
     *
     * <pre>
     *地图模块
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.server.msg.protocol.MsgMap.MapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.msg.protocol.MsgMap.Map.class, com.server.msg.protocol.MsgMap.Map.Builder.class);
      }

      // Construct using com.server.msg.protocol.MsgMap.Map.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEnterSceneRequestFieldBuilder();
          getEnterSceneResPonseFieldBuilder();
          getLoadCompleteFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (enterSceneRequestBuilder_ == null) {
          enterSceneRequest_ = com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.getDefaultInstance();
        } else {
          enterSceneRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (enterSceneResPonseBuilder_ == null) {
          enterSceneResPonse_ = com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.getDefaultInstance();
        } else {
          enterSceneResPonseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (loadCompleteBuilder_ == null) {
          loadComplete_ = com.server.msg.protocol.MsgMap.Map.LoadComplete.getDefaultInstance();
        } else {
          loadCompleteBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.msg.protocol.MsgMap.internal_static_com_server_msg_protocol_Map_descriptor;
      }

      public com.server.msg.protocol.MsgMap.Map getDefaultInstanceForType() {
        return com.server.msg.protocol.MsgMap.Map.getDefaultInstance();
      }

      public com.server.msg.protocol.MsgMap.Map build() {
        com.server.msg.protocol.MsgMap.Map result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.server.msg.protocol.MsgMap.Map buildPartial() {
        com.server.msg.protocol.MsgMap.Map result = new com.server.msg.protocol.MsgMap.Map(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (enterSceneRequestBuilder_ == null) {
          result.enterSceneRequest_ = enterSceneRequest_;
        } else {
          result.enterSceneRequest_ = enterSceneRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (enterSceneResPonseBuilder_ == null) {
          result.enterSceneResPonse_ = enterSceneResPonse_;
        } else {
          result.enterSceneResPonse_ = enterSceneResPonseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (loadCompleteBuilder_ == null) {
          result.loadComplete_ = loadComplete_;
        } else {
          result.loadComplete_ = loadCompleteBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.msg.protocol.MsgMap.Map) {
          return mergeFrom((com.server.msg.protocol.MsgMap.Map)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.msg.protocol.MsgMap.Map other) {
        if (other == com.server.msg.protocol.MsgMap.Map.getDefaultInstance()) return this;
        if (other.hasEnterSceneRequest()) {
          mergeEnterSceneRequest(other.getEnterSceneRequest());
        }
        if (other.hasEnterSceneResPonse()) {
          mergeEnterSceneResPonse(other.getEnterSceneResPonse());
        }
        if (other.hasLoadComplete()) {
          mergeLoadComplete(other.getLoadComplete());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.msg.protocol.MsgMap.Map parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.msg.protocol.MsgMap.Map) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;
      private com.server.msg.protocol.MsgMap.Map.EnterSceneRequest enterSceneRequest_ = com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.server.msg.protocol.MsgMap.Map.EnterSceneRequest, com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.Builder, com.server.msg.protocol.MsgMap.Map.EnterSceneRequestOrBuilder> enterSceneRequestBuilder_;
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
       */
      public boolean hasEnterSceneRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
       */
      public com.server.msg.protocol.MsgMap.Map.EnterSceneRequest getEnterSceneRequest() {
        if (enterSceneRequestBuilder_ == null) {
          return enterSceneRequest_;
        } else {
          return enterSceneRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
       */
      public Builder setEnterSceneRequest(com.server.msg.protocol.MsgMap.Map.EnterSceneRequest value) {
        if (enterSceneRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          enterSceneRequest_ = value;
          onChanged();
        } else {
          enterSceneRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
       */
      public Builder setEnterSceneRequest(
          com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.Builder builderForValue) {
        if (enterSceneRequestBuilder_ == null) {
          enterSceneRequest_ = builderForValue.build();
          onChanged();
        } else {
          enterSceneRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
       */
      public Builder mergeEnterSceneRequest(com.server.msg.protocol.MsgMap.Map.EnterSceneRequest value) {
        if (enterSceneRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              enterSceneRequest_ != com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.getDefaultInstance()) {
            enterSceneRequest_ =
              com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.newBuilder(enterSceneRequest_).mergeFrom(value).buildPartial();
          } else {
            enterSceneRequest_ = value;
          }
          onChanged();
        } else {
          enterSceneRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
       */
      public Builder clearEnterSceneRequest() {
        if (enterSceneRequestBuilder_ == null) {
          enterSceneRequest_ = com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.getDefaultInstance();
          onChanged();
        } else {
          enterSceneRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
       */
      public com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.Builder getEnterSceneRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getEnterSceneRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
       */
      public com.server.msg.protocol.MsgMap.Map.EnterSceneRequestOrBuilder getEnterSceneRequestOrBuilder() {
        if (enterSceneRequestBuilder_ != null) {
          return enterSceneRequestBuilder_.getMessageOrBuilder();
        } else {
          return enterSceneRequest_;
        }
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneRequest enterSceneRequest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.server.msg.protocol.MsgMap.Map.EnterSceneRequest, com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.Builder, com.server.msg.protocol.MsgMap.Map.EnterSceneRequestOrBuilder> 
          getEnterSceneRequestFieldBuilder() {
        if (enterSceneRequestBuilder_ == null) {
          enterSceneRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.server.msg.protocol.MsgMap.Map.EnterSceneRequest, com.server.msg.protocol.MsgMap.Map.EnterSceneRequest.Builder, com.server.msg.protocol.MsgMap.Map.EnterSceneRequestOrBuilder>(
                  enterSceneRequest_,
                  getParentForChildren(),
                  isClean());
          enterSceneRequest_ = null;
        }
        return enterSceneRequestBuilder_;
      }

      // optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;
      private com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse enterSceneResPonse_ = com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse, com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.Builder, com.server.msg.protocol.MsgMap.Map.EnterSceneResPonseOrBuilder> enterSceneResPonseBuilder_;
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
       */
      public boolean hasEnterSceneResPonse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
       */
      public com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse getEnterSceneResPonse() {
        if (enterSceneResPonseBuilder_ == null) {
          return enterSceneResPonse_;
        } else {
          return enterSceneResPonseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
       */
      public Builder setEnterSceneResPonse(com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse value) {
        if (enterSceneResPonseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          enterSceneResPonse_ = value;
          onChanged();
        } else {
          enterSceneResPonseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
       */
      public Builder setEnterSceneResPonse(
          com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.Builder builderForValue) {
        if (enterSceneResPonseBuilder_ == null) {
          enterSceneResPonse_ = builderForValue.build();
          onChanged();
        } else {
          enterSceneResPonseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
       */
      public Builder mergeEnterSceneResPonse(com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse value) {
        if (enterSceneResPonseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              enterSceneResPonse_ != com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.getDefaultInstance()) {
            enterSceneResPonse_ =
              com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.newBuilder(enterSceneResPonse_).mergeFrom(value).buildPartial();
          } else {
            enterSceneResPonse_ = value;
          }
          onChanged();
        } else {
          enterSceneResPonseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
       */
      public Builder clearEnterSceneResPonse() {
        if (enterSceneResPonseBuilder_ == null) {
          enterSceneResPonse_ = com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.getDefaultInstance();
          onChanged();
        } else {
          enterSceneResPonseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
       */
      public com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.Builder getEnterSceneResPonseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getEnterSceneResPonseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
       */
      public com.server.msg.protocol.MsgMap.Map.EnterSceneResPonseOrBuilder getEnterSceneResPonseOrBuilder() {
        if (enterSceneResPonseBuilder_ != null) {
          return enterSceneResPonseBuilder_.getMessageOrBuilder();
        } else {
          return enterSceneResPonse_;
        }
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.EnterSceneResPonse enterSceneResPonse = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse, com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.Builder, com.server.msg.protocol.MsgMap.Map.EnterSceneResPonseOrBuilder> 
          getEnterSceneResPonseFieldBuilder() {
        if (enterSceneResPonseBuilder_ == null) {
          enterSceneResPonseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse, com.server.msg.protocol.MsgMap.Map.EnterSceneResPonse.Builder, com.server.msg.protocol.MsgMap.Map.EnterSceneResPonseOrBuilder>(
                  enterSceneResPonse_,
                  getParentForChildren(),
                  isClean());
          enterSceneResPonse_ = null;
        }
        return enterSceneResPonseBuilder_;
      }

      // optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;
      private com.server.msg.protocol.MsgMap.Map.LoadComplete loadComplete_ = com.server.msg.protocol.MsgMap.Map.LoadComplete.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.server.msg.protocol.MsgMap.Map.LoadComplete, com.server.msg.protocol.MsgMap.Map.LoadComplete.Builder, com.server.msg.protocol.MsgMap.Map.LoadCompleteOrBuilder> loadCompleteBuilder_;
      /**
       * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
       */
      public boolean hasLoadComplete() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
       */
      public com.server.msg.protocol.MsgMap.Map.LoadComplete getLoadComplete() {
        if (loadCompleteBuilder_ == null) {
          return loadComplete_;
        } else {
          return loadCompleteBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
       */
      public Builder setLoadComplete(com.server.msg.protocol.MsgMap.Map.LoadComplete value) {
        if (loadCompleteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          loadComplete_ = value;
          onChanged();
        } else {
          loadCompleteBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
       */
      public Builder setLoadComplete(
          com.server.msg.protocol.MsgMap.Map.LoadComplete.Builder builderForValue) {
        if (loadCompleteBuilder_ == null) {
          loadComplete_ = builderForValue.build();
          onChanged();
        } else {
          loadCompleteBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
       */
      public Builder mergeLoadComplete(com.server.msg.protocol.MsgMap.Map.LoadComplete value) {
        if (loadCompleteBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              loadComplete_ != com.server.msg.protocol.MsgMap.Map.LoadComplete.getDefaultInstance()) {
            loadComplete_ =
              com.server.msg.protocol.MsgMap.Map.LoadComplete.newBuilder(loadComplete_).mergeFrom(value).buildPartial();
          } else {
            loadComplete_ = value;
          }
          onChanged();
        } else {
          loadCompleteBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
       */
      public Builder clearLoadComplete() {
        if (loadCompleteBuilder_ == null) {
          loadComplete_ = com.server.msg.protocol.MsgMap.Map.LoadComplete.getDefaultInstance();
          onChanged();
        } else {
          loadCompleteBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
       */
      public com.server.msg.protocol.MsgMap.Map.LoadComplete.Builder getLoadCompleteBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLoadCompleteFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
       */
      public com.server.msg.protocol.MsgMap.Map.LoadCompleteOrBuilder getLoadCompleteOrBuilder() {
        if (loadCompleteBuilder_ != null) {
          return loadCompleteBuilder_.getMessageOrBuilder();
        } else {
          return loadComplete_;
        }
      }
      /**
       * <code>optional .com.server.msg.protocol.Map.LoadComplete loadComplete = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.server.msg.protocol.MsgMap.Map.LoadComplete, com.server.msg.protocol.MsgMap.Map.LoadComplete.Builder, com.server.msg.protocol.MsgMap.Map.LoadCompleteOrBuilder> 
          getLoadCompleteFieldBuilder() {
        if (loadCompleteBuilder_ == null) {
          loadCompleteBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.server.msg.protocol.MsgMap.Map.LoadComplete, com.server.msg.protocol.MsgMap.Map.LoadComplete.Builder, com.server.msg.protocol.MsgMap.Map.LoadCompleteOrBuilder>(
                  loadComplete_,
                  getParentForChildren(),
                  isClean());
          loadComplete_ = null;
        }
        return loadCompleteBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.server.msg.protocol.Map)
    }

    static {
      defaultInstance = new Map(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.server.msg.protocol.Map)
  }

  public static final int MAP_FIELD_NUMBER = 102;
  /**
   * <code>extend .com.server.msg.protocol.Message { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.server.msg.protocol.Msg.Message,
      com.server.msg.protocol.MsgMap.Map> map = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.server.msg.protocol.MsgMap.Map.class,
        com.server.msg.protocol.MsgMap.Map.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_server_msg_protocol_Map_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_server_msg_protocol_Map_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_server_msg_protocol_Map_EnterSceneRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_server_msg_protocol_Map_EnterSceneRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_server_msg_protocol_Map_EnterSceneResPonse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_server_msg_protocol_Map_EnterSceneResPonse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_server_msg_protocol_Map_LoadComplete_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_server_msg_protocol_Map_LoadComplete_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmsg_map.proto\022\027com.server.msg.protocol" +
      "\032\tmsg.proto\"\352\002\n\003Map\022I\n\021enterSceneRequest" +
      "\030\001 \001(\0132..com.server.msg.protocol.Map.Ent" +
      "erSceneRequest\022K\n\022enterSceneResPonse\030\002 \001" +
      "(\0132/.com.server.msg.protocol.Map.EnterSc" +
      "eneResPonse\022?\n\014loadComplete\030\003 \001(\0132).com." +
      "server.msg.protocol.Map.LoadComplete\032+\n\021" +
      "EnterSceneRequest\022\017\n\007sceneId\030\002 \001(\005:\005\220\202\031\270" +
      "\027\032F\n\022EnterSceneResPonse\022)\n\003pos\030\002 \001(\0132\034.c" +
      "om.server.msg.protocol.Pos:\005\220\202\031\271\027\032\025\n\014Loa",
      "dComplete:\005\220\202\031\272\027:K\n\003map\022 .com.server.msg" +
      ".protocol.Message\030f \001(\0132\034.com.server.msg" +
      ".protocol.Map"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_server_msg_protocol_Map_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_server_msg_protocol_Map_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_server_msg_protocol_Map_descriptor,
              new java.lang.String[] { "EnterSceneRequest", "EnterSceneResPonse", "LoadComplete", });
          internal_static_com_server_msg_protocol_Map_EnterSceneRequest_descriptor =
            internal_static_com_server_msg_protocol_Map_descriptor.getNestedTypes().get(0);
          internal_static_com_server_msg_protocol_Map_EnterSceneRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_server_msg_protocol_Map_EnterSceneRequest_descriptor,
              new java.lang.String[] { "SceneId", });
          internal_static_com_server_msg_protocol_Map_EnterSceneResPonse_descriptor =
            internal_static_com_server_msg_protocol_Map_descriptor.getNestedTypes().get(1);
          internal_static_com_server_msg_protocol_Map_EnterSceneResPonse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_server_msg_protocol_Map_EnterSceneResPonse_descriptor,
              new java.lang.String[] { "Pos", });
          internal_static_com_server_msg_protocol_Map_LoadComplete_descriptor =
            internal_static_com_server_msg_protocol_Map_descriptor.getNestedTypes().get(2);
          internal_static_com_server_msg_protocol_Map_LoadComplete_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_server_msg_protocol_Map_LoadComplete_descriptor,
              new java.lang.String[] { });
          map.internalInit(descriptor.getExtensions().get(0));
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(com.server.msg.protocol.Msg.msgId);
          registry.add(com.server.msg.protocol.Msg.msgId);
          registry.add(com.server.msg.protocol.Msg.msgId);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.server.msg.protocol.Msg.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
