// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_map.proto

package com.server.message.protocol;

public final class MsgMap {
  private MsgMap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.server.message.protocol.MsgMap.EnterSceneRequest.enterSceneRequest);
    registry.add(com.server.message.protocol.MsgMap.EnterSceneResPonse.enterSceneResPonse);
  }
  public interface EnterSceneRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 sceneId = 2;
    /**
     * <code>optional int32 sceneId = 2;</code>
     */
    boolean hasSceneId();
    /**
     * <code>optional int32 sceneId = 2;</code>
     */
    int getSceneId();
  }
  /**
   * Protobuf type {@code com.server.message.protocol.EnterSceneRequest}
   *
   * <pre>
   *地图模块
   * </pre>
   */
  public static final class EnterSceneRequest extends
      com.google.protobuf.GeneratedMessage
      implements EnterSceneRequestOrBuilder {
    // Use EnterSceneRequest.newBuilder() to construct.
    private EnterSceneRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EnterSceneRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EnterSceneRequest defaultInstance;
    public static EnterSceneRequest getDefaultInstance() {
      return defaultInstance;
    }

    public EnterSceneRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EnterSceneRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              sceneId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.message.protocol.MsgMap.internal_static_com_server_message_protocol_EnterSceneRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.message.protocol.MsgMap.internal_static_com_server_message_protocol_EnterSceneRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.message.protocol.MsgMap.EnterSceneRequest.class, com.server.message.protocol.MsgMap.EnterSceneRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<EnterSceneRequest> PARSER =
        new com.google.protobuf.AbstractParser<EnterSceneRequest>() {
      public EnterSceneRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnterSceneRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EnterSceneRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 sceneId = 2;
    public static final int SCENEID_FIELD_NUMBER = 2;
    private int sceneId_;
    /**
     * <code>optional int32 sceneId = 2;</code>
     */
    public boolean hasSceneId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 sceneId = 2;</code>
     */
    public int getSceneId() {
      return sceneId_;
    }

    private void initFields() {
      sceneId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, sceneId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sceneId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.server.message.protocol.MsgMap.EnterSceneRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.server.message.protocol.MsgMap.EnterSceneRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.server.message.protocol.EnterSceneRequest}
     *
     * <pre>
     *地图模块
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.server.message.protocol.MsgMap.EnterSceneRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.message.protocol.MsgMap.internal_static_com_server_message_protocol_EnterSceneRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.message.protocol.MsgMap.internal_static_com_server_message_protocol_EnterSceneRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.message.protocol.MsgMap.EnterSceneRequest.class, com.server.message.protocol.MsgMap.EnterSceneRequest.Builder.class);
      }

      // Construct using com.server.message.protocol.MsgMap.EnterSceneRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sceneId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.message.protocol.MsgMap.internal_static_com_server_message_protocol_EnterSceneRequest_descriptor;
      }

      public com.server.message.protocol.MsgMap.EnterSceneRequest getDefaultInstanceForType() {
        return com.server.message.protocol.MsgMap.EnterSceneRequest.getDefaultInstance();
      }

      public com.server.message.protocol.MsgMap.EnterSceneRequest build() {
        com.server.message.protocol.MsgMap.EnterSceneRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.server.message.protocol.MsgMap.EnterSceneRequest buildPartial() {
        com.server.message.protocol.MsgMap.EnterSceneRequest result = new com.server.message.protocol.MsgMap.EnterSceneRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sceneId_ = sceneId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.message.protocol.MsgMap.EnterSceneRequest) {
          return mergeFrom((com.server.message.protocol.MsgMap.EnterSceneRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.message.protocol.MsgMap.EnterSceneRequest other) {
        if (other == com.server.message.protocol.MsgMap.EnterSceneRequest.getDefaultInstance()) return this;
        if (other.hasSceneId()) {
          setSceneId(other.getSceneId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.message.protocol.MsgMap.EnterSceneRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.message.protocol.MsgMap.EnterSceneRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 sceneId = 2;
      private int sceneId_ ;
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      public boolean hasSceneId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      public int getSceneId() {
        return sceneId_;
      }
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      public Builder setSceneId(int value) {
        bitField0_ |= 0x00000001;
        sceneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sceneId = 2;</code>
       */
      public Builder clearSceneId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sceneId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.server.message.protocol.EnterSceneRequest)
    }

    static {
      defaultInstance = new EnterSceneRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.server.message.protocol.EnterSceneRequest)
    public static final int ENTERSCENEREQUEST_FIELD_NUMBER = 1101;
    /**
     * <code>extend .com.server.message.protocol.Message { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.server.message.protocol.Msg.Message,
        com.server.message.protocol.MsgMap.EnterSceneRequest> enterSceneRequest = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.server.message.protocol.MsgMap.EnterSceneRequest.getDefaultInstance(),
          0,
          com.server.message.protocol.MsgMap.EnterSceneRequest.class,
          com.server.message.protocol.MsgMap.EnterSceneRequest.getDefaultInstance());
  }

  public interface EnterSceneResPonseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .com.server.message.protocol.Pos pos = 2;
    /**
     * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
     */
    boolean hasPos();
    /**
     * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
     */
    com.server.message.protocol.Msg.Pos getPos();
    /**
     * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
     */
    com.server.message.protocol.Msg.PosOrBuilder getPosOrBuilder();
  }
  /**
   * Protobuf type {@code com.server.message.protocol.EnterSceneResPonse}
   */
  public static final class EnterSceneResPonse extends
      com.google.protobuf.GeneratedMessage
      implements EnterSceneResPonseOrBuilder {
    // Use EnterSceneResPonse.newBuilder() to construct.
    private EnterSceneResPonse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EnterSceneResPonse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EnterSceneResPonse defaultInstance;
    public static EnterSceneResPonse getDefaultInstance() {
      return defaultInstance;
    }

    public EnterSceneResPonse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EnterSceneResPonse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              com.server.message.protocol.Msg.Pos.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = pos_.toBuilder();
              }
              pos_ = input.readMessage(com.server.message.protocol.Msg.Pos.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pos_);
                pos_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.server.message.protocol.MsgMap.internal_static_com_server_message_protocol_EnterSceneResPonse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.server.message.protocol.MsgMap.internal_static_com_server_message_protocol_EnterSceneResPonse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.server.message.protocol.MsgMap.EnterSceneResPonse.class, com.server.message.protocol.MsgMap.EnterSceneResPonse.Builder.class);
    }

    public static com.google.protobuf.Parser<EnterSceneResPonse> PARSER =
        new com.google.protobuf.AbstractParser<EnterSceneResPonse>() {
      public EnterSceneResPonse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnterSceneResPonse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EnterSceneResPonse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .com.server.message.protocol.Pos pos = 2;
    public static final int POS_FIELD_NUMBER = 2;
    private com.server.message.protocol.Msg.Pos pos_;
    /**
     * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
     */
    public boolean hasPos() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
     */
    public com.server.message.protocol.Msg.Pos getPos() {
      return pos_;
    }
    /**
     * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
     */
    public com.server.message.protocol.Msg.PosOrBuilder getPosOrBuilder() {
      return pos_;
    }

    private void initFields() {
      pos_ = com.server.message.protocol.Msg.Pos.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, pos_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, pos_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.server.message.protocol.MsgMap.EnterSceneResPonse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneResPonse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneResPonse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneResPonse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneResPonse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneResPonse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneResPonse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneResPonse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneResPonse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.server.message.protocol.MsgMap.EnterSceneResPonse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.server.message.protocol.MsgMap.EnterSceneResPonse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.server.message.protocol.EnterSceneResPonse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.server.message.protocol.MsgMap.EnterSceneResPonseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.server.message.protocol.MsgMap.internal_static_com_server_message_protocol_EnterSceneResPonse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.server.message.protocol.MsgMap.internal_static_com_server_message_protocol_EnterSceneResPonse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.server.message.protocol.MsgMap.EnterSceneResPonse.class, com.server.message.protocol.MsgMap.EnterSceneResPonse.Builder.class);
      }

      // Construct using com.server.message.protocol.MsgMap.EnterSceneResPonse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (posBuilder_ == null) {
          pos_ = com.server.message.protocol.Msg.Pos.getDefaultInstance();
        } else {
          posBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.server.message.protocol.MsgMap.internal_static_com_server_message_protocol_EnterSceneResPonse_descriptor;
      }

      public com.server.message.protocol.MsgMap.EnterSceneResPonse getDefaultInstanceForType() {
        return com.server.message.protocol.MsgMap.EnterSceneResPonse.getDefaultInstance();
      }

      public com.server.message.protocol.MsgMap.EnterSceneResPonse build() {
        com.server.message.protocol.MsgMap.EnterSceneResPonse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.server.message.protocol.MsgMap.EnterSceneResPonse buildPartial() {
        com.server.message.protocol.MsgMap.EnterSceneResPonse result = new com.server.message.protocol.MsgMap.EnterSceneResPonse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (posBuilder_ == null) {
          result.pos_ = pos_;
        } else {
          result.pos_ = posBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.server.message.protocol.MsgMap.EnterSceneResPonse) {
          return mergeFrom((com.server.message.protocol.MsgMap.EnterSceneResPonse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.server.message.protocol.MsgMap.EnterSceneResPonse other) {
        if (other == com.server.message.protocol.MsgMap.EnterSceneResPonse.getDefaultInstance()) return this;
        if (other.hasPos()) {
          mergePos(other.getPos());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.server.message.protocol.MsgMap.EnterSceneResPonse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.server.message.protocol.MsgMap.EnterSceneResPonse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .com.server.message.protocol.Pos pos = 2;
      private com.server.message.protocol.Msg.Pos pos_ = com.server.message.protocol.Msg.Pos.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.server.message.protocol.Msg.Pos, com.server.message.protocol.Msg.Pos.Builder, com.server.message.protocol.Msg.PosOrBuilder> posBuilder_;
      /**
       * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
       */
      public boolean hasPos() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
       */
      public com.server.message.protocol.Msg.Pos getPos() {
        if (posBuilder_ == null) {
          return pos_;
        } else {
          return posBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
       */
      public Builder setPos(com.server.message.protocol.Msg.Pos value) {
        if (posBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pos_ = value;
          onChanged();
        } else {
          posBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
       */
      public Builder setPos(
          com.server.message.protocol.Msg.Pos.Builder builderForValue) {
        if (posBuilder_ == null) {
          pos_ = builderForValue.build();
          onChanged();
        } else {
          posBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
       */
      public Builder mergePos(com.server.message.protocol.Msg.Pos value) {
        if (posBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              pos_ != com.server.message.protocol.Msg.Pos.getDefaultInstance()) {
            pos_ =
              com.server.message.protocol.Msg.Pos.newBuilder(pos_).mergeFrom(value).buildPartial();
          } else {
            pos_ = value;
          }
          onChanged();
        } else {
          posBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
       */
      public Builder clearPos() {
        if (posBuilder_ == null) {
          pos_ = com.server.message.protocol.Msg.Pos.getDefaultInstance();
          onChanged();
        } else {
          posBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
       */
      public com.server.message.protocol.Msg.Pos.Builder getPosBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPosFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
       */
      public com.server.message.protocol.Msg.PosOrBuilder getPosOrBuilder() {
        if (posBuilder_ != null) {
          return posBuilder_.getMessageOrBuilder();
        } else {
          return pos_;
        }
      }
      /**
       * <code>optional .com.server.message.protocol.Pos pos = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.server.message.protocol.Msg.Pos, com.server.message.protocol.Msg.Pos.Builder, com.server.message.protocol.Msg.PosOrBuilder> 
          getPosFieldBuilder() {
        if (posBuilder_ == null) {
          posBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.server.message.protocol.Msg.Pos, com.server.message.protocol.Msg.Pos.Builder, com.server.message.protocol.Msg.PosOrBuilder>(
                  pos_,
                  getParentForChildren(),
                  isClean());
          pos_ = null;
        }
        return posBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.server.message.protocol.EnterSceneResPonse)
    }

    static {
      defaultInstance = new EnterSceneResPonse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.server.message.protocol.EnterSceneResPonse)
    public static final int ENTERSCENERESPONSE_FIELD_NUMBER = 1102;
    /**
     * <code>extend .com.server.message.protocol.Message { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.server.message.protocol.Msg.Message,
        com.server.message.protocol.MsgMap.EnterSceneResPonse> enterSceneResPonse = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.server.message.protocol.MsgMap.EnterSceneResPonse.getDefaultInstance(),
          0,
          com.server.message.protocol.MsgMap.EnterSceneResPonse.class,
          com.server.message.protocol.MsgMap.EnterSceneResPonse.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_server_message_protocol_EnterSceneRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_server_message_protocol_EnterSceneRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_server_message_protocol_EnterSceneResPonse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_server_message_protocol_EnterSceneResPonse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmsg_map.proto\022\033com.server.message.prot" +
      "ocol\032\tmsg.proto\"\235\001\n\021EnterSceneRequest\022\017\n" +
      "\007sceneId\030\002 \001(\0052p\n\021enterSceneRequest\022$.co" +
      "m.server.message.protocol.Message\030\315\010 \001(\013" +
      "2..com.server.message.protocol.EnterScen" +
      "eRequest:\005\220\202\031\315\010\"\276\001\n\022EnterSceneResPonse\022-" +
      "\n\003pos\030\002 \001(\0132 .com.server.message.protoco" +
      "l.Pos2r\n\022EnterSceneResPonse\022$.com.server" +
      ".message.protocol.Message\030\316\010 \001(\0132/.com.s" +
      "erver.message.protocol.EnterSceneResPons",
      "e:\005\220\202\031\316\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_server_message_protocol_EnterSceneRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_server_message_protocol_EnterSceneRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_server_message_protocol_EnterSceneRequest_descriptor,
              new java.lang.String[] { "SceneId", });
          internal_static_com_server_message_protocol_EnterSceneResPonse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_server_message_protocol_EnterSceneResPonse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_server_message_protocol_EnterSceneResPonse_descriptor,
              new java.lang.String[] { "Pos", });
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(com.server.message.protocol.Msg.msgId);
          registry.add(com.server.message.protocol.Msg.msgId);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.server.message.protocol.Msg.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
